FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

USER root

WORKDIR /app

COPY run.sh /app/run.sh

RUN apt-get update && \
    apt-get install -y nginx && \
    apt-get install -y curl && \
    apt-get install -y gcc libfcgi-dev spawn-fcgi && \
    chmod +x /app/run.sh && \
    rm -rf /var/lib/apt/lists && \
    useradd magmarco && \
    mkdir -p /var/cache/nginx /var/log/nginx && \ 
    mkdir -p /var/lib/nginx/body && \ 
    chown -R magmarco:magmarco /var/cache/nginx /var/log/nginx && \ 
    chown -R magmarco:magmarco /etc/nginx/nginx.conf && \
    chown -R magmarco:magmarco /var/lib/nginx/ && \
    chown -R magmarco:magmarco /var/lib/nginx/body && \
    chown -R magmarco:magmarco /app && \
    touch /var/run/nginx.pid && \
    chown -R magmarco:magmarco /var/run/nginx.pid && \
    chmod +x /app/run.sh && \
    chmod u-s /usr/bin/passwd && \
    chmod u-s /usr/bin/newgrp && \
    chmod g-s /usr/bin/chage && \
    chmod u-s /usr/bin/gpasswd && \
    chmod u-s /bin/su && \
    chmod u-s /bin/mount && \
    chmod g-s /usr/bin/wall && \
    chmod u-s /usr/bin/chsh && \
    chmod g-s /usr/bin/expiry && \
    chmod u-s /usr/bin/chfn && \
    chmod u-s /bin/umount && \
    chmod g-s /sbin/unix_chkpwd ;

USER magmarco

EXPOSE 80

COPY server.c /app/server.c
COPY nginx.conf /etc/nginx/nginx.conf

HEALTHCHECK --interval=5s --timeout=3s \
CMD curl -f http://localhost/ || exit 1 

ENTRYPOINT ["/app/run.sh"]