FROM nginx:latest

WORKDIR /home/

COPY ./run.sh /home/run.sh

RUN apt-get update && \
    apt-get install -y gcc libfcgi-dev spawn-fcgi && \
    chmod +x /home/run.sh

COPY server.c /home/server.c
COPY nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT ["./run.sh"]
